create table if not exists public.erp_employees (
  id bigint generated by default as identity primary key,
  name text not null,
  department text not null default '경영지원',
  join_date date not null,
  annual_allowance numeric(5,1),
  created_at timestamptz not null default now()
);

create table if not exists public.erp_leave_entries (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references public.erp_employees(id) on delete cascade,
  leave_date date not null,
  amount numeric(3,1) not null check (amount in (0.5, 1.0)),
  leave_type text not null default 'full' check (leave_type in ('full', 'half-am', 'half-pm')),
  note text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists erp_leave_entries_employee_idx on public.erp_leave_entries(employee_id);
create index if not exists erp_leave_entries_date_idx on public.erp_leave_entries(leave_date desc);

alter table public.erp_employees enable row level security;
alter table public.erp_leave_entries enable row level security;

revoke all on table public.erp_employees from anon, authenticated;
revoke all on table public.erp_leave_entries from anon, authenticated;
grant all on table public.erp_employees to service_role;
grant all on table public.erp_leave_entries to service_role;
grant usage, select on all sequences in schema public to service_role;
