alter table public.erp_employees
  add column if not exists position text not null default '담당자',
  add column if not exists email text not null default '',
  add column if not exists phone text not null default '',
  add column if not exists birth_date date,
  add column if not exists address text not null default '',
  add column if not exists emergency_contact text not null default '',
  add column if not exists employment_status text not null default 'active'
    check (employment_status in ('active', 'leave', 'retired')),
  add column if not exists memo text not null default '',
  add column if not exists updated_at timestamptz not null default now();

create table if not exists public.erp_employment_contracts (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references public.erp_employees(id) on delete cascade,
  contract_type text not null default 'permanent'
    check (contract_type in ('permanent', 'fixed', 'part-time', 'freelance')),
  start_date date not null,
  end_date date,
  monthly_salary numeric(14,0) not null default 0 check (monthly_salary >= 0),
  weekly_hours numeric(5,1) not null default 40 check (weekly_hours >= 0),
  work_start_time time not null default '09:00',
  work_end_time time not null default '18:00',
  probation_end_date date,
  status text not null default 'active' check (status in ('draft', 'active', 'expired')),
  memo text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.erp_expenses (
  id bigint generated by default as identity primary key,
  expense_date date not null,
  category text not null,
  description text not null,
  vendor text not null default '',
  amount numeric(14,0) not null check (amount >= 0),
  payment_method text not null default '법인카드',
  payment_status text not null default 'paid' check (payment_status in ('paid', 'scheduled')),
  memo text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists erp_contracts_employee_idx on public.erp_employment_contracts(employee_id);
create index if not exists erp_contracts_end_date_idx on public.erp_employment_contracts(end_date);
create index if not exists erp_expenses_date_idx on public.erp_expenses(expense_date desc);
create index if not exists erp_expenses_category_idx on public.erp_expenses(category);

alter table public.erp_employment_contracts enable row level security;
alter table public.erp_expenses enable row level security;

revoke all on table public.erp_employment_contracts from anon, authenticated;
revoke all on table public.erp_expenses from anon, authenticated;
grant all on table public.erp_employment_contracts to service_role;
grant all on table public.erp_expenses to service_role;
grant usage, select on all sequences in schema public to service_role;
