create table if not exists public.erp_company_cards (
  id bigint generated by default as identity primary key,
  card_company text not null,
  card_name text not null default '',
  card_alias text not null,
  card_last4 text not null check (card_last4 ~ '^\d{4}$'),
  holder_name text not null default '',
  credit_limit numeric(14,0) not null default 0 check (credit_limit >= 0),
  status text not null default 'active' check (status in ('active', 'inactive')),
  issued_date date,
  expiry_month text check (expiry_month is null or expiry_month ~ '^\d{4}-(0[1-9]|1[0-2])$'),
  responsible_employee_id bigint references public.erp_employees(id) on delete set null,
  memo text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.erp_bank_accounts (
  id bigint generated by default as identity primary key,
  bank_name text not null,
  account_name text not null default '',
  account_alias text not null,
  account_number text not null,
  account_type text not null default 'checking' check (account_type in ('checking', 'savings', 'loan', 'other')),
  balance numeric(14,0) not null default 0,
  status text not null default 'active' check (status in ('active', 'inactive')),
  opened_date date,
  responsible_employee_id bigint references public.erp_employees(id) on delete set null,
  purpose text not null default '',
  memo text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.erp_card_usages (
  id bigint generated by default as identity primary key,
  company_card_id bigint references public.erp_company_cards(id) on delete set null,
  evidence_method text not null default 'corporate-card'
    check (evidence_method in ('corporate-card', 'tax-invoice', 'cash-receipt', 'other')),
  transaction_date date not null,
  merchant text not null,
  amount numeric(14,0) not null default 0 check (amount >= 0),
  requested_amount numeric(14,0) not null default 0 check (requested_amount >= 0),
  purpose text not null,
  user_employee_id bigint references public.erp_employees(id) on delete set null,
  evidence_status text not null default 'missing' check (evidence_status in ('missing', 'submitted', 'confirmed')),
  due_date date,
  receipt_url text not null default '',
  memo text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists erp_company_cards_status_idx on public.erp_company_cards(status);
create index if not exists erp_company_cards_responsible_idx on public.erp_company_cards(responsible_employee_id);
create index if not exists erp_bank_accounts_status_idx on public.erp_bank_accounts(status);
create index if not exists erp_bank_accounts_responsible_idx on public.erp_bank_accounts(responsible_employee_id);
create index if not exists erp_card_usages_date_idx on public.erp_card_usages(transaction_date desc);
create index if not exists erp_card_usages_status_idx on public.erp_card_usages(evidence_status);
create index if not exists erp_card_usages_card_idx on public.erp_card_usages(company_card_id);

alter table public.erp_company_cards enable row level security;
alter table public.erp_bank_accounts enable row level security;
alter table public.erp_card_usages enable row level security;

revoke all on table public.erp_company_cards from anon, authenticated;
revoke all on table public.erp_bank_accounts from anon, authenticated;
revoke all on table public.erp_card_usages from anon, authenticated;
grant all on table public.erp_company_cards to service_role;
grant all on table public.erp_bank_accounts to service_role;
grant all on table public.erp_card_usages to service_role;
grant usage, select on all sequences in schema public to service_role;
