create table if not exists public.erp_revenues (
  id bigint generated by default as identity primary key,
  revenue_date date not null,
  category text not null,
  description text not null,
  client text not null default '',
  amount numeric(14,0) not null check (amount >= 0),
  payment_method text not null default '계좌이체',
  payment_status text not null default 'received' check (payment_status in ('received', 'expected')),
  memo text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists erp_revenues_date_idx on public.erp_revenues(revenue_date desc);
create index if not exists erp_revenues_category_idx on public.erp_revenues(category);

alter table public.erp_revenues enable row level security;
revoke all on table public.erp_revenues from anon, authenticated;
grant all on table public.erp_revenues to service_role;
grant usage, select on all sequences in schema public to service_role;
