create table if not exists public.erp_hr_settings (
  id bigint generated by default as identity primary key,
  kind text not null check (kind in ('department', 'position')),
  value text not null check (char_length(value) between 1 and 50),
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  unique (kind, value)
);

insert into public.erp_hr_settings (kind, value, sort_order) values
  ('department', '콘텐츠팀', 10),
  ('department', '마케팅팀', 20),
  ('department', '디자인팀', 30),
  ('department', '개발팀', 40),
  ('department', '경영지원', 50),
  ('position', '대표', 10),
  ('position', '팀장', 20),
  ('position', '매니저', 30),
  ('position', '사원', 40)
on conflict (kind, value) do nothing;

alter table public.erp_hr_settings enable row level security;
revoke all on table public.erp_hr_settings from anon, authenticated;
grant all on table public.erp_hr_settings to service_role;
grant usage, select on all sequences in schema public to service_role;
