alter table public.erp_expenses
  add column if not exists employee_id bigint;

alter table public.erp_expenses
  drop constraint if exists erp_expenses_employee_id_fkey;

alter table public.erp_expenses
  add constraint erp_expenses_employee_id_fkey
  foreign key (employee_id)
  references public.erp_employees(id)
  on delete set null;

create index if not exists erp_expenses_employee_id_idx
  on public.erp_expenses(employee_id);

create table if not exists public.erp_payrolls (
  id bigint generated by default as identity primary key,
  payroll_month text not null check (payroll_month ~ '^\d{4}-\d{2}$'),
  employee_id bigint not null references public.erp_employees(id) on delete cascade,
  base_pay numeric(14,0) not null default 0 check (base_pay >= 0),
  meal_allowance numeric(14,0) not null default 0 check (meal_allowance >= 0),
  childcare_allowance numeric(14,0) not null default 0 check (childcare_allowance >= 0),
  fixed_overtime_pay numeric(14,0) not null default 0 check (fixed_overtime_pay >= 0),
  holiday_pay numeric(14,0) not null default 0 check (holiday_pay >= 0),
  research_allowance numeric(14,0) not null default 0 check (research_allowance >= 0),
  other_allowance numeric(14,0) not null default 0 check (other_allowance >= 0),
  total_pay numeric(14,0) not null default 0 check (total_pay >= 0),
  pension_base numeric(14,0) not null default 0 check (pension_base >= 0),
  health_base numeric(14,0) not null default 0 check (health_base >= 0),
  employment_base numeric(14,0) not null default 0 check (employment_base >= 0),
  auto_insurance boolean not null default true,
  national_pension numeric(14,0) not null default 0 check (national_pension >= 0),
  health_insurance numeric(14,0) not null default 0 check (health_insurance >= 0),
  long_term_care numeric(14,0) not null default 0 check (long_term_care >= 0),
  employment_insurance numeric(14,0) not null default 0 check (employment_insurance >= 0),
  income_tax numeric(14,0) not null default 0 check (income_tax >= 0),
  local_income_tax numeric(14,0) not null default 0 check (local_income_tax >= 0),
  other_deduction numeric(14,0) not null default 0 check (other_deduction >= 0),
  total_deduction numeric(14,0) not null default 0 check (total_deduction >= 0),
  net_pay numeric(14,0) not null default 0 check (net_pay >= 0),
  payment_status text not null default 'draft' check (payment_status in ('draft', 'confirmed', 'paid')),
  payment_date date,
  rate_year integer not null default 2026,
  memo text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (payroll_month, employee_id)
);

create index if not exists erp_payrolls_month_idx on public.erp_payrolls(payroll_month desc);
create index if not exists erp_payrolls_employee_idx on public.erp_payrolls(employee_id);

alter table public.erp_payrolls enable row level security;
revoke all on table public.erp_payrolls from anon, authenticated;
grant all on table public.erp_payrolls to service_role;
grant usage, select on all sequences in schema public to service_role;
